CREATE TABLE student (
  STUDENT_ID       INT         AUTO_INCREMENT COMMENT '主键ID',
  STUDENT_NAME     VARCHAR(20) NOT NULL       COMMENT '姓名',
  STUDENT_AGE      INT         NOT NULL       COMMENT '年龄',
  STUDENT_BIRTHDAY DATE        NOT NULL       COMMENT '生日',
  PRIMARY KEY (STUDENT_ID)
) CHARSET = utf8;